### ISSUE TITLE
The correct command might be goodOrBad instead of GoodLinkOrBadLink

### ISSUE THREAD

**Issue by abuZayed15** [yuanLeeMidori/OSD600.GoodLinkOrBadLink#1]
When running the application, the correct command should **goodOrBad** but the the CLI suggests using GoodLinkOrBadLink.

![image](https://user-images.githubusercontent.com/36981880/94217078-1c8dac00-feaf-11ea-9c96-4f71e64841d1.png)

**Comment by yuanLeeMidori** [comment]
Thank you. It should be fixed. Please check the relevant commit.

**Comment by yuanLeeMidori** [comment]
Hi, thank you for filing the issue :+1: 
This issue has been fixed in the latest version of source code and nuget package.

**Comment by abuZayed15** [comment]
Thanks!
