### ISSUE TITLE
Adding --ignore feature

### ISSUE THREAD

**Issue by abuZayed15** [yuanLeeMidori/OSD600.GoodLinkOrBadLink#14]
This feature will ignore all the URLs in a file that are immediately followed by a `# Ignore all` line.

### Requirements
`--ignore` , `-i` . `\i` are optional flags that should be present in order to invoke the ignore feature

**Comment by yuanLeeMidori** [comment]
https://github.com/yuanLeeMidori/OSD600.GoodLinkOrBadLink/commit/4e896a9cfad031c389a136e1aadf8825d395db69
