### ISSUE TITLE
Current version might not be displayed

### ISSUE THREAD

**Issue by abuZayed15** [yuanLeeMidori/OSD600.GoodLinkOrBadLink#2]
The correct version might not be displayed on the screen. The only output I get when I run `goodOrBad -v` or `goodOrBad -version` is `Warning: Could not find file '{filePath}\OSD600.GoodLinkOrBadLink-master\-version'.` and `Warning: Could not find file 'D:\Documents\Seneca College\OSD600\YuanLeeRelease0.1\OSD600.GoodLinkOrBadLink-master\--version'.`

![image](https://user-images.githubusercontent.com/36981880/94217631-7d69b400-feb0-11ea-9fcf-c524030081c1.png)

**Comment by yuanLeeMidori** [comment]
Hi, thank you for filing this issue. The issue has been fixed and you can see the correct version number without warning message.

**Comment by abuZayed15** [comment]
Thanks!
