### ISSUE TITLE
Separate class files

### ISSUE THREAD

**Issue by abuZayed15** [yuanLeeMidori/OSD600.GoodLinkOrBadLink#4]
Having separate class files that are specialized to do certain tasks. Similar to the concept of separation of concerns. It might help with reading the code a little better. :) 

![image](https://user-images.githubusercontent.com/36981880/94219582-2dd9b700-feb5-11ea-8de5-c79103e479ab.png)

**Comment by yuanLeeMidori** [comment]
This issue has been solved by [this commit](https://github.com/yuanLeeMidori/OSD600.GoodLinkOrBadLink/commit/2a54f4b7bf7b40851d7b698a9c54872331435308) and [that commit](https://github.com/yuanLeeMidori/OSD600.GoodLinkOrBadLink/commit/18ea7fb48725146059a39212cfa8af4209449dba). Thank you for reporting this issue!
