### ISSUE TITLE
Adding Wayback Machine flag

### ISSUE THREAD

**Issue by rogercyyu** [yuanLeeMidori/OSD600.GoodLinkOrBadLink#6]
Hi, I would like to add an optional feature where it checks Wayback Machine's API and checks whether a copy of the site is store there. I would most likely add a new flag `goodOrbad -w ` or `goodOrBad  --wayback`. See [this ](https://archive.org/help/wayback_api.php) for more information. Thank-you.

**Comment by yuanLeeMidori** [comment]
This feature has been added to the project by @rogercyyu
